# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f154090cadb84162c5dd65fb73bf306305c55eb0dfd56668355a476274cb958501fa3d03152781b2fb8267ca5cfde65226013d8adb91cd8a8fe29f1f626ff82e

test:
  secret_key_base: 0598260217e57fe7ab2f7bba5f2cfe7b4e6a90c891881c63609c423fc3cfbd611d4c8b77d291c2ab4821a8329dc30df4468ec110b670df303a89623ad80be2fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
